version: '3.8'
services:
  dbt_demo:
    build:
      context: .      
    image: beachsensorsproject
    container_name: dbt-beach-sensors
    volumes:
      - ./dbt_project:/dbt_project
    command: tail -f /dev/null
    ports:
      - "8080:8080"