beach_sensors:
  outputs:
    blue:
      type: duckdb
      path: dev.duckdb
      threads: 1
      schema: dbt_blue
    green:
      type: duckdb
      path: dev.duckdb
      threads: 1
      schema: dbt_green
    main: 
      type: duckdb
      path: dev.duckdb
      threads: 1
      schema: main
  target: blue